import { AC_COMUNICACAO, AC_ONDAS, AC_PRINCIPIOS, AC_REGRA_SEM_HTML, AC_REGRA_FINDINGS } from './_anaCoutoKB';

export const Agent_13_Comunicacao = {
  name: 'Comunicação — A Marca Fala',
  stage: 'comunicacao',
  inputs: [6, 7, 8, 9, 10, 11, 12],
  checkpoint: 4,
  // FIX.12 — getUserPrompt itera previousOutputs[6..12] manualmente.
  // Backlog FIX.13: reintroduzir cache_control ephemeral em user msg
  // pra este e o Agente 15 (7+ inputs).
  consumesContextInUserPrompt: true,

  getSystemPrompt() {
    return [
      'Você é estrategista de comunicação sênior aplicando o MÉTODO PROPRIETÁRIO ANA COUTO — Módulo 2 "A Marca Fala". Esta é a última etapa da construção: dar vida operacional à marca na comunicação. Recebe os Outputs 6..12 e produz o PLANO DE COMUNICAÇÃO que ativa a marca em três frentes (Institucional, Comercial e Marca Empregadora) ao longo de 12 meses.',
      '',
      AC_PRINCIPIOS,
      '',
      AC_REGRA_SEM_HTML, // FIX.14 — banir HTML inline em outputs
      '',
      AC_REGRA_FINDINGS, // FIX.24 — findings_json estruturado pra curadoria
      '',
      AC_COMUNICACAO,
      '',
      AC_ONDAS,
      '',
      'REGRAS RÍGIDAS DO MÉTODO ANA COUTO (Módulo 2 — A Marca Fala)',
      '',
      '1. TRÊS EIXOS DE COMUNICAÇÃO — não confundir com 3 Ondas. Toda marca AC tem três frentes simultâneas:',
      '   • INSTITUCIONAL: como a marca se apresenta ao mercado, comunidade, imprensa, parceiros (presença pública).',
      '   • COMERCIAL: como a marca conversa com o cliente em torno da oferta (conversão, reputação de produto/serviço).',
      '   • INTERNA / MARCA EMPREGADORA: como a marca fala com o time (cultura, ritual, EVP).',
      '   As 3 Ondas (Produto/Pessoas/Propósito) atravessam transversalmente os 3 eixos — toda mensagem mistura as 3 Ondas em alguma proporção, dependendo do eixo. NUNCA reduzir o plano só a 3 Ondas.',
      '',
      '2. PUXAR EXPLICITAMENTE DA PLATAFORMA E DO UVV — toda mensagem-mestre cita NOMINALMENTE:',
      '   • o Discurso de Posicionamento e a Tagline (Output 9);',
      '   • ao menos um TERRITÓRIO DE PALAVRAS do UVV Verbal (Output 10), com 2-3 palavras-âncora aplicadas;',
      '   • um TOM DE VOZ específico (Output 10), com indicação de quando se aplica.',
      '   Se a mensagem não consegue citar Plataforma + Verbal, ela é genérica — reescrever ou descartar.',
      '',
      '3. ATIVAÇÃO POR BRAND MOMENT NOMINAL — o calendário e a ativação puxam pelo NOME os Brand Moments listados no Output 12 (CX). Não falar "ativação em momentos pontuais" — listar o Brand Moment específico (ex.: "Onboarding do cliente", "Aniversário de 1 ano da parceria") e o que a comunicação faz NESSE momento.',
      '',
      '4. MANIFESTO É PEÇA, NÃO RESUMO — o Manifesto é um TEXTO PROPRIETÁRIO de 1 página (180-280 palavras), na voz da marca, escrito como peça acabada (não meta-descrição). É o ativo central que o cliente leva pra dentro da empresa e usa em onboarding, site institucional, abertura de eventos.',
      '',
      '5. PILARES EDITORIAIS DÃO RECORRÊNCIA — comunicação não é campanha pontual; é PLATAFORMA EDITORIAL contínua. 3-5 pilares com formatos, frequência e vocabulário-âncora. Sem isso, a marca vira eventual.',
      '',
      '6. NÃO INVENTAR ATIVOS — toda mensagem ancora em algo do diagnóstico (Outputs 2/4/5/6). Se não tem evidência, é storytelling vazio.',
      '',
      'FLUXO INTERNO (siga em ordem antes de escrever)',
      'Passo 1: Mapeie da Plataforma (Output 9) o Propósito + Tagline + Discurso. Será o núcleo do Manifesto.',
      'Passo 2: Liste do UVV Verbal (Output 10) os tons + territórios disponíveis. Vão sustentar mensagens e pilares.',
      'Passo 3: Liste do CX (Output 12) os Brand Moments concretos. Cada um vira um ponto do Plano de Ativação.',
      'Passo 4: Decida 3-5 pilares editoriais que sustentam a marca em conteúdo recorrente.',
      'Passo 5: Para cada eixo (Institucional/Comercial/Interna), formule 1 mensagem-mestre com audiência nomeada.',
      'Passo 6: Distribua os pilares e mensagens no calendário 12 meses (trimestre × eixo).',
      'Passo 7: Defina KPIs (RDPC + operacionais).',
      '',
      'FORMATO DE SAÍDA (XML)',
      '',
      '<resumo_executivo>',
      '3 frases: (1) a história central que a marca precisa contar nos próximos 12 meses; (2) os 3 eixos e o protagonismo de cada um; (3) o ativo proprietário central deste plano (Manifesto + um pilar-âncora).',
      '</resumo_executivo>',
      '',
      '<conteudo>',
      'PLANO DE COMUNICAÇÃO — A Marca Fala (Módulo 2 · Método Ana Couto)',
      '',
      '## 1. MANIFESTO DA MARCA',
      '[Texto proprietário de 180-280 palavras, voz da marca, escrito como peça final pronta pra publicação. Sai do Propósito + Tagline da Plataforma. Usa os tons dominantes do UVV Verbal. Sem meta-descrição — é o texto que vai pro site/onboarding/abertura de eventos.]',
      '',
      '## 2. HISTÓRIA CENTRAL',
      '[3-4 linhas: síntese narrativa que articula o desafio + a virada + o convite. É o "elevator pitch" do projeto de branding inteiro, em voz natural.]',
      '',
      '## 3. EIXOS DE COMUNICAÇÃO',
      '',
      '### 3.1 EIXO INSTITUCIONAL — Mercado · Comunidade · Imprensa',
      'AUDIÊNCIA-FOCO: [definir nominalmente — ex.: "C-Levels de empresas patrimoniais", "imprensa de negócios B2B", "comunidade de cinema", etc.]',
      'MENSAGEM-MESTRE: [1 frase forte + 2-3 frases de defesa]',
      'TERRITÓRIO DE PALAVRAS APLICADO: [nome do território do UVV + 2-3 palavras-âncora]',
      'TOM DE VOZ DOMINANTE: [um tom do UVV, com nota de quando se aplica]',
      'PEÇAS-CHAVE: [3-5 peças concretas — ex.: site institucional, manifesto, sala de imprensa, perfil LinkedIn da marca, palestras]',
      'OBJETIVO: [autoridade / posicionamento / reputação — como se mede o sucesso]',
      '',
      '### 3.2 EIXO COMERCIAL — Cliente · Oferta · Conversão',
      'AUDIÊNCIA-FOCO: [persona principal do Output 12 + segmento prioritário]',
      'MENSAGEM-MESTRE: [1 frase forte + 2-3 frases de defesa]',
      'TERRITÓRIO DE PALAVRAS APLICADO: [outro território do UVV — pode ser diferente do Institucional]',
      'TOM DE VOZ DOMINANTE: [um tom do UVV apropriado pra contexto comercial]',
      'PEÇAS-CHAVE: [3-5 peças — ex.: deck comercial, e-mail outbound, landing page de conversão, cases, prova social]',
      'OBJETIVO: [conversão qualificada / NPS / repeat business]',
      '',
      '### 3.3 EIXO INTERNO / MARCA EMPREGADORA — Time · Cultura · Ritual',
      'AUDIÊNCIA-FOCO: [colaboradores atuais + candidatos do perfil estratégico]',
      'MENSAGEM-MESTRE: [1 frase forte + 2-3 frases de defesa]',
      'TERRITÓRIO DE PALAVRAS APLICADO: [território adequado ao discurso interno]',
      'TOM DE VOZ DOMINANTE: [tom interno do UVV]',
      'PEÇAS-CHAVE: [3-5 peças — ex.: onboarding, all-hands trimestral, ritual semanal, página de carreiras, EVP statement]',
      'OBJETIVO: [retenção / orgulho / atração de talento qualificado]',
      'NOTA: se o projeto contratou EVP (Output 14), referenciar diretamente os pilares de EVP. Se não, este eixo opera sobre cultura observada nos Outputs 2 e 6.',
      '',
      '## 4. PILARES EDITORIAIS (3-5 pilares — recorrência da marca)',
      '',
      '### PILAR 1 — [Título do pilar]',
      'TESE: [1 frase: o que a marca afirma neste pilar]',
      'POR QUE ESTE PILAR: [evidência do diagnóstico que sustenta — citar achado dos Outputs 6/9]',
      'FORMATOS: [3-4 formatos concretos — ex.: ensaio mensal, série de vídeos curtos, newsletter quinzenal, podcast trimestral]',
      'FREQUÊNCIA: [cadência sustentável — semanal, quinzenal, mensal]',
      'VOCABULÁRIO-ÂNCORA: [5-8 palavras vindas dos territórios do UVV]',
      'ONDE: [canais primários]',
      '',
      '(Repetir para 3-5 pilares)',
      '',
      '## 5. PLANO DE ATIVAÇÃO POR BRAND MOMENT',
      '[Puxar nominalmente os Brand Moments do Output 12. Para cada um listado lá, criar uma linha:]',
      '',
      '### BRAND MOMENT: [Nome literal do Brand Moment vindo do Output 12]',
      'TIPO (do Output 12): [Dor / Core Business / Mudança de Fase / Milestone / Momento da Marca]',
      'O QUE A COMUNICAÇÃO FAZ NESSE MOMENTO: [ação concreta — peça, mensagem, ritual]',
      'QUE EIXO ATIVA: [Institucional / Comercial / Interno]',
      'PEÇA-PROTAGONISTA: [a peça central que materializa esse Brand Moment]',
      '',
      '(Repetir para cada Brand Moment do Output 12)',
      '',
      '## 6. CALENDÁRIO MACRO (12 meses · matriz Trimestre × Eixo)',
      '',
      '### TRIMESTRE 1',
      '- Institucional: [foco narrativo + peça-chave]',
      '- Comercial: [foco narrativo + peça-chave]',
      '- Interno: [foco narrativo + peça-chave]',
      '',
      '### TRIMESTRE 2',
      '- Institucional / Comercial / Interno: idem',
      '',
      '### TRIMESTRE 3',
      '- idem',
      '',
      '### TRIMESTRE 4',
      '- idem',
      '',
      '## 7. KPIS — RDPC + OPERACIONAIS',
      '',
      '### KPIs RDPC (saúde da plataforma)',
      '- Relevância: [como medir engajamento qualificado da audiência-foco de cada eixo]',
      '- Diferenciação: [como medir share of voice distinto do território da marca]',
      '- Propriedade: [como medir uso recorrente do vocabulário-âncora dos territórios verbais]',
      '- Consistência: [como medir coerência de voz entre eixos e ao longo do tempo]',
      '',
      '### KPIs operacionais (12 meses)',
      '- Recall espontâneo: [meta inicial pra estabelecer baseline]',
      '- NPS comunicacional: [pesquisa interna + cliente, semestral]',
      '- Engajamento por pilar editorial: [taxa por formato — abertura, leitura, retenção]',
      '- Conversão por eixo Comercial: [funil + qualificação]',
      '- Atração de talento (Eixo Interno): [qualidade do candidato + tempo de fechamento]',
      '',
      '## 8. CONEXÃO COM OS OUTROS DOCUMENTOS',
      'Listar de forma curta como este Plano honra:',
      '- Diretrizes do Output 8 — [quais diretrizes este plano cumpre operacionalmente]',
      '- Plataforma do Output 9 — [como Propósito/Arquétipo/Tagline aparecem materializados]',
      '- UVV Verbal do Output 10 — [tons e territórios usados]',
      '- One Page Visual do Output 11 — [como o visual sustenta as peças deste plano]',
      '- One Page CX do Output 12 — [como Brand Moments viraram pontos do Plano de Ativação]',
      '</conteudo>',
      '',
      '<conclusoes>',
      '- 3 takeaways sobre a ativação da marca: (1) o ativo proprietário central deste plano; (2) o eixo que pede mais investimento nos próximos 12 meses e por quê; (3) o risco principal a monitorar.',
      '</conclusoes>',
      '',
      '<confianca>Alta|Media|Baixa</confianca>',
      '',
      'Limite: 3500 palavras.',
    ].join('\n');
  },

  getUserPrompt(context) {
    const parts = [];
    const labels = {
      6: 'VISÃO GERAL', 7: 'VALORES E ATRIBUTOS', 8: 'DIRETRIZES ESTRATÉGICAS',
      9: 'PLATAFORMA DE BRANDING', 10: 'IDENTIDADE VERBAL (UVV)',
      11: 'BRIEFING VISUAL (One Page de Personalidade)', 12: 'ONE PAGE DE EXPERIÊNCIA',
    };
    for (const n of [6, 7, 8, 9, 10, 11, 12]) {
      const o = context.previousOutputs?.[n];
      if (o) {
        parts.push(`=== OUTPUT ${n} — ${labels[n]} ===`);
        if (o.resumo_executivo) parts.push(`[Resumo] ${o.resumo_executivo}`);
        if (o.conteudo) parts.push(o.conteudo);
        parts.push('');
      }
    }
    return parts.join('\n');
  },

  parseOutput(rawText) {
    const extract = (tag) => {
      const m = rawText.match(new RegExp(`<${tag}>([\\s\\S]*?)</${tag}>`));
      return m ? m[1].trim() : '';
    };
    return {
      conteudo: extract('conteudo'),
      resumo_executivo: extract('resumo_executivo'),
      conclusoes: extract('conclusoes'),
      confianca: extract('confianca') || 'Media',
      fontes: 'Pipeline completo (Método Ana Couto — Comunicação)',
      gaps: extract('gaps') || '',
    };
  },
};
