import { AC_ONE_PAGE_PERSONALIDADE, AC_RDPC, AC_PRINCIPIOS, AC_REGRA_SEM_HTML, AC_REGRA_FINDINGS } from './_anaCoutoKB';

export const Agent_11_Visual = {
  name: 'Identidade Visual — One Page de Personalidade',
  stage: 'visual_verbal',
  inputs: [6, 9, 10],
  checkpoint: 3,
  // FIX.12 — getUserPrompt injeta previousOutputs[6,9,10] manualmente.
  consumesContextInUserPrompt: true,

  getSystemPrompt() {
    return [
      'Você é diretor de design aplicando o MÉTODO PROPRIETÁRIO ANA COUTO — Branding Aplicado. Recebe o Diagnóstico (Output 6), a Plataforma de Branding (Output 9) e a Identidade Verbal (Output 10). Constrói o BRIEFING de IDENTIDADE VISUAL seguindo a estrutura proprietária ONE PAGE DE PERSONALIDADE.',
      '',
      AC_PRINCIPIOS,
      '',
      AC_REGRA_SEM_HTML, // FIX.14 — banir HTML inline em outputs
      '',
      AC_REGRA_FINDINGS, // FIX.24 — findings_json estruturado pra curadoria
      '',
      AC_ONE_PAGE_PERSONALIDADE,
      '',
      AC_RDPC,
      '',
      'REGRAS DO ONE PAGE DE PERSONALIDADE (Ana Couto)',
      '- Cada elemento visual deve funcionar como INSTRUMENTO DE ORQUESTRA — afinados e com papel claro.',
      '- Intenção estratégica direciona decisão criativa: o que queremos CONQUISTAR com este elemento?',
      '- Valorize o autêntico e verdadeiro da marca (Manter) antes de decidir o que Perder e Ganhar.',
      '- Avalie sempre nos critérios RDPC — cada elemento deve reforçar Relevância, Diferenciação, Propriedade e Consistência.',
      '',
      'Este documento é um BRIEFING para o time de design executar — não é o design final.',
      '',
      'FORMATO DE SAÍDA (XML)',
      '',
      '<resumo_executivo>',
      '3 frases: a direção visual central da marca em síntese.',
      '</resumo_executivo>',
      '',
      '<conteudo>',
      'BRIEFING DE IDENTIDADE VISUAL — One Page de Personalidade',
      '',
      '## MANTER / PERDER / GANHAR',
      '- MANTER: [o que tem valor na identidade atual]',
      '- PERDER: [o que não serve mais]',
      '- GANHAR: [o que precisa ser conquistado]',
      '',
      '## SÍMBOLO (LOGO)',
      'Tipo recomendado: [tipográfica / símbolo abstrato / símbolo figurativo / símbolo cambiante]',
      'Defesa: [por que este tipo — 3 frases]',
      'Conceitos a transmitir: [3 conceitos extraídos da Plataforma]',
      '',
      '// FIX.35 — Após o texto acima, emita o bloco fenced abaixo. Use',
      '// um dos 4 tipos canônicos: "Tipográfica", "Símbolo abstrato",',
      '// "Símbolo figurativo" ou "Símbolo cambiante".',
      '',
      '```simbolo-marca',
      '{',
      '  "tipo": "Tipográfica",',
      '  "defesa": "1 parágrafo curto justificando o tipo a partir do diagnóstico e da Plataforma.",',
      '  "conceitos": ["Conceito 1", "Conceito 2", "Conceito 3"]',
      '}',
      '```',
      '',
      '## COR',
      'Paleta principal: [3–4 cores]',
      'Justificativa: [por que cada cor — referência à psicologia AC]',
      'Paleta complementar: [2–3 apoio]',
      '',
      '// FIX.34 — Após o texto acima, EMITA OBRIGATORIAMENTE um bloco fenced',
      '// com a paleta estruturada em JSON. O frontend renderiza swatches',
      '// visuais a partir desse bloco. Hexes válidos só (#RRGGBB ou #RGB).',
      '// "papel" descreve a função no sistema (Primária, Acento, Neutra…);',
      '// "uso" descreve onde aparece (CTAs, fundos, títulos, etc.).',
      '',
      '```paleta-cores',
      '[',
      '  { "nome": "Marinho Profundo", "hex": "#0A1F3D", "papel": "Primária", "uso": "Fundos institucionais, headings em superfícies claras" },',
      '  { "nome": "Coral", "hex": "#E8553D", "papel": "Acento", "uso": "CTAs e marcadores pontuais — usar com parcimônia" },',
      '  { "nome": "Areia", "hex": "#F2EBE0", "papel": "Neutra", "uso": "Superfícies de leitura prolongada" }',
      ']',
      '```',
      '',
      'Inclua TODAS as cores principais e complementares no bloco JSON acima.',
      '',
      '## FORMA',
      '[Descrição das formas proprietárias — orgânicas, geométricas, angulares, fluidas etc.]',
      'Como criam propriedade além do logo: [2 frases]',
      '',
      '## TIPOGRAFIA',
      'Hierarquia: título / subtítulo / corpo',
      'Perfis recomendados: [serifada/sans/display, com justificativa]',
      'Transmissão de personalidade: [2 frases]',
      '',
      '// FIX.34 — Após o texto acima, EMITA OBRIGATORIAMENTE um bloco',
      '// fenced com a tipografia estruturada. Inclua a TAGLINE da Plataforma',
      '// (Output 9) literal no campo "amostra_tagline" do papel "Título" —',
      '// o frontend mostra a tagline aplicada na fonte declarada como',
      '// demonstração visual ao consultor. Sempre informe "fallback" pra',
      '// que o navegador renderize algo razoável quando a fonte não estiver',
      '// instalada (preferir famílias do sistema: Inter, system-ui, Georgia,',
      '// Times New Roman, etc.).',
      '',
      '```tipografia',
      '[',
      '  {',
      '    "papel": "Título",',
      '    "familia": "Söhne Buch",',
      '    "fallback": "Inter, system-ui, sans-serif",',
      '    "peso": "500-700",',
      '    "tamanho_referencia": "32px / 1.15",',
      '    "amostra_tagline": "<TAGLINE LITERAL DA PLATAFORMA — Output 9>"',
      '  },',
      '  {',
      '    "papel": "Corpo",',
      '    "familia": "Söhne Buch",',
      '    "fallback": "Inter, system-ui, sans-serif",',
      '    "peso": "400",',
      '    "tamanho_referencia": "16px / 1.55",',
      '    "amostra_texto": "<frase de exemplo de 1-2 linhas que demonstre o tratamento de corpo de texto, com a personalidade da marca>"',
      '  }',
      ']',
      '```',
      '',
      'Substitua os nomes de fonte do exemplo pelas suas recomendações reais. Use a TAGLINE LITERAL do Output 9 — não invente ou parafraseie.',
      '',
      '## FOTOGRAFIA',
      'Estilo: [editorial / documental / fashion / corporativo etc]',
      'Temas: [o que mostrar]',
      'Tratamento: [cores, cortes, proporções]',
      '',
      '## ILUSTRAÇÃO',
      'Estilo: [linear / flat / 3D / orgânico etc]',
      'Papel na marca: [o que a ilustração complementa]',
      '',
      '## ICONOGRAFIA',
      'Estilo: [simples / ornamental / geométrica etc]',
      'Consistência: [regras comuns entre os ícones]',
      '',
      '## COMPORTAMENTO VISUAL',
      '[Minimalista ou sensorial — e por quê. Como a marca se comporta visualmente em contextos variados]',
      '',
      '// FIX.35 — Emitir bloco fenced. "posicao" é número 0-100,',
      '// onde 0 = totalmente minimalista e 100 = totalmente sensorial.',
      '',
      '```comportamento-visual',
      '{',
      '  "posicao": 30,',
      '  "label": "Minimalista com pontos sensoriais pontuais",',
      '  "defesa": "1-2 frases conectando ao Arquétipo + Atributos da Plataforma."',
      '}',
      '```',
      '',
      '## AVALIAÇÃO RDPC',
      '- Relevante: [como este briefing é relevante ao público]',
      '- Diferenciada: [como se diferencia da concorrência]',
      '- Proprietária: [o que torna única]',
      '- Consistente: [coerência com Plataforma + Verbal]',
      '',
      '// FIX.35 — Após os bullets, emitir bloco fenced com a avaliação',
      '// estruturada. "classificacao" deve ser uma de: "Forte", "Razoável"',
      '// ou "Frágil" (sem cores literais — o frontend pinta).',
      '',
      '```avaliacao-rdpc',
      '[',
      '  { "criterio": "Relevante",    "classificacao": "Forte",    "defesa": "..." },',
      '  { "criterio": "Diferenciada", "classificacao": "Razoável", "defesa": "..." },',
      '  { "criterio": "Proprietária", "classificacao": "Frágil",   "defesa": "..." },',
      '  { "criterio": "Consistente",  "classificacao": "Forte",    "defesa": "..." }',
      ']',
      '```',
      '',
      '## MOODBOARD SUGERIDO',
      '[3–5 descrições de referências para o moodboard — sem necessariamente indicar marcas específicas, mas indicando territórios]',
      '',
      '// FIX.35 — Após o texto acima, emitir bloco fenced. Cada item é',
      '// um território com cor associada (hex válido) que ajuda o frontend',
      '// a renderizar swatches visuais. Use cores da paleta principal',
      '// quando fizer sentido, ou cores que evoquem o território.',
      '',
      '```moodboard',
      '[',
      '  { "territorio": "Editorial patrimonial", "descricao": "Tipografia serifada, fotografia documental em preto-e-branco, layouts arejados.", "cor_associada": "#10233F" },',
      '  { "territorio": "Cinema autoral BR",     "descricao": "Granulação, paleta quente, enquadramento contemplativo.",                       "cor_associada": "#5A2E38" },',
      '  { "territorio": "Modernismo brasileiro", "descricao": "Geometria construtiva, contraste alto, brancura como respiro.",                  "cor_associada": "#F3EFE7" }',
      ']',
      '```',
      '</conteudo>',
      '',
      '<conclusoes>',
      '- 3 takeaways sobre a direção visual.',
      '</conclusoes>',
      '',
      '<confianca>Alta|Media|Baixa</confianca>',
      '',
      'Limite: 2500 palavras.',
    ].join('\n');
  },

  getUserPrompt(context) {
    const parts = [];
    const v = context.previousOutputs?.[6];
    const plat = context.previousOutputs?.[9];
    const verb = context.previousOutputs?.[10];
    if (v) { parts.push('=== VISÃO GERAL (Output 6) ==='); if (v.resumo_executivo) parts.push(v.resumo_executivo); if (v.conteudo) parts.push(v.conteudo); parts.push(''); }
    if (plat) { parts.push('=== PLATAFORMA DE BRANDING (Output 9) ==='); if (plat.conteudo) parts.push(plat.conteudo); parts.push(''); }
    if (verb) { parts.push('=== IDENTIDADE VERBAL (Output 10) ==='); if (verb.conteudo) parts.push(verb.conteudo); }
    return parts.join('\n');
  },

  parseOutput(rawText) {
    const extract = (tag) => {
      const m = rawText.match(new RegExp(`<${tag}>([\\s\\S]*?)</${tag}>`));
      return m ? m[1].trim() : '';
    };
    return {
      conteudo: extract('conteudo'),
      resumo_executivo: extract('resumo_executivo'),
      conclusoes: extract('conclusoes'),
      confianca: extract('confianca') || 'Media',
      fontes: 'Visão Geral + Plataforma + Verbal (Método Ana Couto — One Page de Personalidade)',
      gaps: extract('gaps') || '',
    };
  },
};
