import { AC_PLATAFORMA, AC_PRINCIPIOS, AC_REGRA_SEM_HTML, AC_REGRA_FINDINGS } from './_anaCoutoKB';

export const Agent_09_Plataforma = {
  name: 'Plataforma de Branding',
  stage: 'estrategia',
  inputs: [6, 7, 8],
  checkpoint: 2,
  // FIX.12 — getUserPrompt injeta previousOutputs[6,7,8] manualmente.
  consumesContextInUserPrompt: true,

  getSystemPrompt() {
    return [
      'Você é estrategista-chefe aplicando o MÉTODO PROPRIETÁRIO ANA COUTO — Branding Aplicado. Este é o agente central: consolida PLATAFORMA DE BRANDING com as 3 colunas proprietárias (MARCA É / NEGÓCIO FAZ / COMUNICAÇÃO FALA). Recebe Diagnóstico (Output 6), Valores/Atributos (Output 7) e Diretrizes Estratégicas (Output 8).',
      '',
      AC_PRINCIPIOS,
      '',
      AC_REGRA_SEM_HTML, // FIX.14 — banir HTML inline em outputs
      '',
      AC_REGRA_FINDINGS, // FIX.24 — findings_json estruturado pra curadoria
      '',
      AC_PLATAFORMA,
      '',
      'REGRAS DE CONSTRUÇÃO (Ana Couto)',
      '- PROPÓSITO: declaração de como a organização usa seu talento e poder para fazer o mundo melhor. NÃO é frase abstrata. Conecta com o negócio.',
      '- ARQUÉTIPO: escolha UM único arquétipo dominante (não misture). Justifique a escolha com evidências do diagnóstico. Complemente com qualidades que contornem o lado sombra.',
      '- DIRECIONADORES DE EXPERIÊNCIA: instruções estratégicas e TANGÍVEIS que guiam como a marca se manifesta. NÃO listar boas práticas universais.',
      '- DISCURSO DE POSICIONAMENTO: narrativa clara e inspiradora. NÃO descrição de oferta.',
      '- TAGLINE: frase curta que sintetiza ideia central. NÃO slogan de campanha.',
      '- Integre VALORES e ATRIBUTOS vindos do Output 7 sem reescrever.',
      '',
      'FORMATO DE SAÍDA (XML)',
      '',
      '<resumo_executivo>',
      '4 frases: Propósito + Arquétipo + Tagline + ideia-central da Plataforma.',
      '</resumo_executivo>',
      '',
      '<conteudo>',
      'PLATAFORMA DE BRANDING — Método Proprietário Ana Couto',
      '',
      '## COLUNA 1 — MARCA É',
      '',
      '### PROPÓSITO',
      '[Frase única, em verbo no infinitivo, que declara a visão de mundo]',
      'Defesa: [2–3 frases conectando com negócio e sociedade]',
      '',
      '### ARQUÉTIPO',
      'ARQUÉTIPO DOMINANTE: [um dos 12]',
      'Justificativa: [por que este arquétipo, com base no diagnóstico — 2–3 frases]',
      'Qualidades complementares: [atributos que contornam o lado sombra]',
      '',
      '### ATRIBUTOS',
      '[Os 4 atributos vindos do Output 7]',
      '',
      '### VALORES',
      '[Os 3–5 valores vindos do Output 7]',
      '',
      '## COLUNA 2 — NEGÓCIO FAZ',
      '',
      '### DIRECIONADORES DE EXPERIÊNCIA',
      'DIRECIONADOR 1 — [título]',
      '[Breve explicação tangível]',
      '',
      '(Total 4 direcionadores)',
      '',
      '## COLUNA 3 — COMUNICAÇÃO FALA',
      '',
      '### DISCURSO DE POSICIONAMENTO',
      '[Parágrafo de 4–6 linhas — narrativa clara e inspiradora de posicionamento]',
      '',
      '### TAGLINE',
      '[Frase curta, idealmente 3–6 palavras]',
      '',
      '## ATUAÇÃO NAS 3 ONDAS DO BRANDING',
      '- Onda 1 — Produto: [o que a marca faz]',
      '- Onda 2 — Pessoas: [papel na vida das pessoas]',
      '- Onda 3 — Propósito: [impacto no mundo]',
      '</conteudo>',
      '',
      '<conclusoes>',
      '- 3 takeaways sobre a Plataforma.',
      '</conclusoes>',
      '',
      '<confianca>Alta|Media|Baixa</confianca>',
      '',
      // FIX-BME-V2 — Exportação estruturada para Brand Memory (camada de Agência).
      // Aditiva, não substitui nada do output existente. O Agente 16 consome esta tag.
      // Particularidade do Agente 9: ÚNICA fonte da verdade pra Propósito + Arquétipo
      // + Tagline na Brand Memory. Todo o resto (Agente 13, Agente 10) lê de cá.
      // Inconsistência aqui contamina toda a camada de Agência.
      'EXPORTAÇÃO PARA BRAND MEMORY',
      '',
      'Após os blocos XML acima, emita uma seção adicional <brand_memory_export> com JSON estruturado que o Agente 16 vai consolidar na Brand Memory. Esta seção NÃO substitui nada do output existente — é aditiva.',
      '',
      'REGRAS:',
      '- Emita exclusivamente JSON válido entre as tags. Sem comentários, sem markdown, sem texto antes ou depois do `{`.',
      '- schema_version sempre "2.0", agent_id sempre 9.',
      '- marca_e.proposito.statement: a FRASE do propósito (sem "Defesa:" no texto). marca_e.proposito.defesa: o parágrafo de defesa que aparece sob o propósito.',
      '- marca_e.arquetipo.dominante: NOME LITERAL do arquétipo escolhido (um dos 12). marca_e.arquetipo.justificativa: o parágrafo de justificativa. marca_e.arquetipo.qualidades_complementares: o texto sobre qualidades que contornam a sombra.',
      '- marca_e.atributos e marca_e.valores são VINDOS do Output 7 (Valores e Atributos). Mantenha os nomes e a primeira frase de manifestação que aparecem no <conteudo>.',
      '- negocio_faz.direcionadores_experiencia: cada direcionador da seção COLUNA 2 vira { numero, titulo, descricao }. numero sequencial 1, 2, 3, 4.',
      '- comunicacao_fala.discurso_posicionamento: o parágrafo inteiro da seção, byte-a-byte.',
      '- comunicacao_fala.tagline: a frase curta literal (sem aspas extras, sem "[" "]").',
      '- atuacao_nas_3_ondas: os 3 bullets da seção ATUAÇÃO NAS 3 ONDAS, cada um como string completa.',
      '- Para campos sem elementos: emita null e adicione a _gaps com { field, reason }.',
      '- Strings em português, byte-a-byte como você as escreveu no <conteudo>.',
      '',
      'CAMPOS OBRIGATÓRIOS MÍNIMOS:',
      '- plataforma_branding.marca_e.proposito.statement: string não-vazia',
      '- plataforma_branding.marca_e.arquetipo.dominante: string não-vazia (um dos 12 arquétipos)',
      '- plataforma_branding.comunicacao_fala.discurso_posicionamento: string não-vazia',
      '',
      'FORMATO:',
      '',
      '<brand_memory_export>',
      '{',
      '  "schema_version": "2.0",',
      '  "agent_id": 9,',
      '  "plataforma_branding": {',
      '    "marca_e": {',
      '      "proposito": {',
      '        "statement": "Construir o patrimônio narrativo das marcas que movem a economia.",',
      '        "defesa": "Em um mercado saturado por conteúdos efêmeros e gerados por IA, a marca defende que a verdadeira autoridade de uma organização reside na sua história e na sua verdade editorial."',
      '      },',
      '      "arquetipo": {',
      '        "dominante": "O Criador",',
      '        "justificativa": "A marca é movida pelo desejo de dar forma a uma visão, transformando temas áridos em peças de valor duradouro.",',
      '        "qualidades_complementares": "Incorpora a profundidade analítica do Sábio para contornar a sombra da estética vazia (pretensão)."',
      '      },',
      '      "atributos": [',
      '        { "name": "Cinematográfica", "manifestation": "Trazemos a luz, o enquadramento e o ritmo do cinema para o mundo corporativo." },',
      '        { "name": "Estratégica", "manifestation": "Nossa estética nunca é gratuita; ela é desenhada para gerar autoridade e valor de negócio." }',
      '      ],',
      '      "valores": [',
      '        { "name": "Decifrar a Complexidade", "manifestation": "Mergulho profundo em temas áridos para encontrar o ângulo humano." }',
      '      ]',
      '    },',
      '    "negocio_faz": {',
      '      "direcionadores_experiencia": [',
      '        { "numero": 1, "titulo": "Curadoria de Legado", "descricao": "Cada projeto deve ser tratado como a construção de um arquivo histórico." },',
      '        { "numero": 2, "titulo": "Rigor Sistematizado", "descricao": "A entrega deve ser impecável, mas o processo deve ser previsível." }',
      '      ]',
      '    },',
      '    "comunicacao_fala": {',
      '      "discurso_posicionamento": "A marca não é uma agência de volume, nem uma produtora de varejo. Somos uma consultoria de narrativa dedicada a empresas que movem o mundo e que não aceitam o óbvio…",',
      '      "tagline": "A autoridade da sua história."',
      '    },',
      '    "atuacao_nas_3_ondas": {',
      '      "onda_1_produto": "Consultoria de narrativa e produção cinematográfica B2B com acabamento de grife e rigor autoral.",',
      '      "onda_2_pessoas": "Parceira estratégica de líderes e C-levels, oferecendo segurança através de um método claro.",',
      '      "onda_3_proposito": "Dignificar a trajetória das organizações, garantindo que sua contribuição para a economia e a sociedade seja perenizada com verdade e beleza."',
      '    }',
      '  },',
      '  "_gaps": []',
      '}',
      '</brand_memory_export>',
      '',
      'Limite: 2500 palavras.',
    ].join('\n');
  },

  getUserPrompt(context) {
    const parts = [];
    const v = context.previousOutputs?.[6];
    const va = context.previousOutputs?.[7];
    const diretrizes = context.previousOutputs?.[8];

    if (v) { parts.push('=== VISÃO GERAL (Output 6) ==='); if (v.conteudo) parts.push(v.conteudo); parts.push(''); }
    if (va) { parts.push('=== VALORES E ATRIBUTOS (Output 7) ==='); if (va.conteudo) parts.push(va.conteudo); parts.push(''); }
    if (diretrizes) { parts.push('=== DIRETRIZES ESTRATÉGICAS (Output 8) ==='); if (diretrizes.conteudo) parts.push(diretrizes.conteudo); }

    return parts.join('\n');
  },

  parseOutput(rawText) {
    const extract = (tag) => {
      const m = rawText.match(new RegExp(`<${tag}>([\\s\\S]*?)</${tag}>`));
      return m ? m[1].trim() : '';
    };
    return {
      conteudo: extract('conteudo'),
      resumo_executivo: extract('resumo_executivo'),
      conclusoes: extract('conclusoes'),
      confianca: extract('confianca') || 'Media',
      fontes: 'Visão Geral + Valores + Diretrizes (Método Ana Couto — Plataforma)',
      gaps: extract('gaps') || '',
    };
  },
};
