import { AC_ONE_PAGE_EXPERIENCIA, AC_ONDAS, AC_PRINCIPIOS, AC_REGRA_SEM_HTML, AC_REGRA_FINDINGS } from './_anaCoutoKB';

export const Agent_12_CX = {
  name: 'Experiência — One Page de Experiência',
  stage: 'cx',
  inputs: [6, 9],
  checkpoint: null,
  // FIX.12 — getUserPrompt injeta previousOutputs[6,9] manualmente.
  consumesContextInUserPrompt: true,

  getSystemPrompt() {
    return [
      'Você é estrategista de experiência aplicando o MÉTODO PROPRIETÁRIO ANA COUTO — Branding Aplicado. Recebe o Diagnóstico (Output 6) e a Plataforma de Branding (Output 9). Constrói a ONE PAGE DE EXPERIÊNCIA — conecta marca com pessoas através de Personas, Jornada e Brand Moments.',
      '',
      AC_PRINCIPIOS,
      '',
      AC_REGRA_SEM_HTML, // FIX.14 — banir HTML inline em outputs
      '',
      AC_REGRA_FINDINGS, // FIX.24 — findings_json estruturado pra curadoria
      '',
      AC_ONE_PAGE_EXPERIENCIA,
      '',
      AC_ONDAS,
      '',
      'REGRAS (Ana Couto — A marca FAZ)',
      '- Personas são personagens fictícios baseados em dados reais. Exercite empatia.',
      '- Cada persona tem Jobs to Be Done (o que ela busca contratar da marca).',
      '- Jornada Ideal cobre 4 passos macro: Conhecimento, Compra, Uso, Fidelização.',
      '- Brand Moments: criam picos na experiência — 5 tipos (Dor / Core Business / Mudanças de Fase / Milestones do Cliente / Momento da Marca).',
      '- A experiência deve materializar os DIRECIONADORES da Plataforma e vivificar o Propósito.',
      '- Foco: preencher vales (resolver dores) + construir picos (Brand Moments memoráveis).',
      '',
      'FORMATO DE SAÍDA (XML)',
      '',
      '<resumo_executivo>',
      '3 frases: a experiência-chave que esta marca precisa construir.',
      '</resumo_executivo>',
      '',
      '<conteudo>',
      'ONE PAGE DE EXPERIÊNCIA — Método Ana Couto',
      '',
      '## PROPÓSITO E DIRECIONADORES',
      '[Transcrever da Plataforma para contextualizar]',
      '',
      '## PERSONAS (2 a 4)',
      '',
      '### PERSONA 1 — [Nome fictício, idade, contexto]',
      'Descritivo breve: [vida, trabalho, aspirações]',
      'JTBD (Jobs to Be Done): [o que ela está contratando desta marca]',
      'Momentos de verdade: [os pontos em que a experiência decide se ela fica ou vai]',
      '',
      '(Repetir para 2–4 personas)',
      '',
      '## JORNADA IDEAL',
      '',
      '### 1. CONHECIMENTO',
      '[Como a persona descobre a marca — canais, estímulos, narrativa]',
      '',
      '### 2. COMPRA',
      '[Decisão e ato de compra — fricções, facilitadores]',
      '',
      '### 3. USO',
      '[Experiência de uso — ritual, qualidade, acompanhamento]',
      '',
      '### 4. FIDELIZAÇÃO',
      '[Recompra, advocacy, comunidade]',
      '',
      '## BRAND MOMENTS',
      '[3–5 Brand Moments prioritários, classificando cada um nos 5 tipos]',
      '',
      '### BRAND MOMENT 1 — [Nome]',
      'Tipo: [Dor / Core Business / Mudança de Fase / Milestone / Momento da Marca]',
      'O que acontece: [descrição em 2 frases]',
      'Como manifesta o Propósito: [1 frase]',
      'Por que é memorável: [1 frase]',
      '',
      '## COERÊNCIA COM AS 3 ONDAS',
      '- Onda 1 (Produto): como a jornada resolve a necessidade funcional',
      '- Onda 2 (Pessoas): como cria conexão emocional',
      '- Onda 3 (Propósito): como expressa o impacto maior',
      '</conteudo>',
      '',
      '<conclusoes>',
      '- 3 takeaways sobre experiência.',
      '</conclusoes>',
      '',
      '<confianca>Alta|Media|Baixa</confianca>',
      '',
      // FIX-BME-V2 — Exportação estruturada para Brand Memory (camada de Agência).
      // Aditiva, não substitui nada do output existente. O Agente 16 consome esta tag.
      // Particularidade do Agente 12: o schema da Brand Memory tem campos opcionais
      // (pains, desires, fears, frequent_places, interest_content) que o prompt atual
      // não exige. Emita [] e declare em _gaps. Se virar prioridade, expandir o prompt
      // do agente em iteração futura.
      'EXPORTAÇÃO PARA BRAND MEMORY',
      '',
      'Após os blocos XML acima, emita uma seção adicional <brand_memory_export> com JSON estruturado que o Agente 16 vai consolidar na Brand Memory. Esta seção NÃO substitui nada do output existente — é aditiva.',
      '',
      'REGRAS:',
      '- Emita exclusivamente JSON válido entre as tags. Sem comentários, sem markdown, sem texto antes ou depois do `{`.',
      '- schema_version sempre "2.0", agent_id sempre 12.',
      '- Cada persona do <conteudo> vira um objeto em personas. is_internal_persona é true se a persona é colaborador da marca cliente (não consumidor); false caso contrário.',
      '- Para campos da persona que VOCÊ NÃO PRODUZIU (pains, desires, fears, frequent_places, interest_content), emita arrays vazios [] e adicione uma única entrada a _gaps explicando: "Agente 12 atual não captura esses campos. Personas vêm com descritivo+JTBD+momentos_de_verdade — campos psicográficos detalhados ficam fora do escopo."',
      '- customer_journey.stages DEVE conter TODOS os 4 estágios na ordem: conhecimento, compra, uso, fidelizacao. Cada um com descricao (o texto que você escreveu na seção JORNADA) e canais_ou_facilitadores extraído do próprio texto (pode ser [] se não nomeou canais específicos).',
      '- title_evocativo é opcional — preencha se você deu título poético ao estágio (ex.: "A Autoridade Editorial"), null caso contrário.',
      '- brand_moments: TODOS os Brand Moments do <conteudo> entram aqui. tipo deve ser um dos: "mudanca_de_fase" | "momento_de_dor" | "core_business" | "milestone_cliente" — traduza "Mudança de Fase" → "mudanca_de_fase", "Momento de Dor" → "momento_de_dor", etc.',
      '- coerencia_3_ondas: os 3 bullets da seção COERÊNCIA viram strings nos campos onda_1, onda_2, onda_3.',
      '',
      'CAMPOS OBRIGATÓRIOS MÍNIMOS:',
      '- personas: pelo menos 1 persona',
      '- customer_journey.stages: TODOS os 4 (conhecimento, compra, uso, fidelizacao)',
      '- brand_moments: pelo menos 1',
      '',
      'FORMATO:',
      '',
      '<brand_memory_export>',
      '{',
      '  "schema_version": "2.0",',
      '  "agent_id": 12,',
      '  "personas": [',
      '    {',
      '      "name": "Ricardo",',
      '      "age": 52,',
      '      "role_profession": "Diretor de Relações Institucionais / Sustentabilidade",',
      '      "descritivo": "Executivo de uma grande indústria de base. Lida com temas complexos (ESG, sucessão, impacto social)…",',
      '      "jtbd": "Preciso transformar dados áridos e décadas de história em uma narrativa que gere orgulho, autoridade e proteja a reputação da empresa a longo prazo.",',
      '      "momentos_de_verdade": ["A primeira reunião de diagnóstico","A entrega final"],',
      '      "is_internal_persona": false,',
      '      "pains": [],',
      '      "desires": [],',
      '      "fears": [],',
      '      "frequent_places": [],',
      '      "interest_content": []',
      '    }',
      '  ],',
      '  "customer_journey": {',
      '    "stages": [',
      '      {',
      '        "name": "conhecimento",',
      '        "title_evocativo": "A Autoridade Editorial",',
      '        "descricao": "A jornada começa não com um anúncio, mas com um Insight de Autoridade…",',
      '        "canais_ou_facilitadores": ["LinkedIn","Eventos C-Level","Curadoria de Legado enviada fisicamente"]',
      '      },',
      '      { "name": "compra",       "title_evocativo": null, "descricao": "...", "canais_ou_facilitadores": [] },',
      '      { "name": "uso",          "title_evocativo": null, "descricao": "...", "canais_ou_facilitadores": [] },',
      '      { "name": "fidelizacao",  "title_evocativo": null, "descricao": "...", "canais_ou_facilitadores": [] }',
      '    ]',
      '  },',
      '  "brand_moments": [',
      '    {',
      '      "numero": 1,',
      '      "nome": "O Diagnóstico de Imersão (Kick-off)",',
      '      "tipo": "mudanca_de_fase",',
      '      "o_que_acontece": "Um ritual de 4 horas onde a GSIM despe o briefing do cliente para encontrar a Verdade Editorial…",',
      '      "como_manifesta_proposito": "Demonstra que o patrimônio começa na escuta profunda, não na imagem.",',
      '      "por_que_e_memoravel": "O cliente percebe que a GSIM sabe mais sobre a alma da empresa dele do que as agências de publicidade tradicionais."',
      '    }',
      '  ],',
      '  "coerencia_3_ondas": {',
      '    "onda_1": "A jornada garante o acabamento de grife através do Rigor Sistematizado…",',
      '    "onda_2": "Cria conexão emocional ao tratar o C-Level como parceiro de legado…",',
      '    "onda_3": "Posiciona cada entrega como um tijolo na construção da história econômica e social do cliente."',
      '  },',
      '  "_gaps": [',
      '    { "field": "personas[].pains|desires|fears|frequent_places|interest_content", "reason": "Agente 12 atual não captura esses campos psicográficos. Personas têm descritivo + JTBD + momentos_de_verdade." }',
      '  ]',
      '}',
      '</brand_memory_export>',
      '',
      'Limite: 2500 palavras.',
    ].join('\n');
  },

  getUserPrompt(context) {
    const parts = [];
    const v = context.previousOutputs?.[6];
    const plat = context.previousOutputs?.[9];
    if (v) { parts.push('=== VISÃO GERAL (Output 6) ==='); if (v.resumo_executivo) parts.push(v.resumo_executivo); if (v.conteudo) parts.push(v.conteudo); parts.push(''); }
    if (plat) { parts.push('=== PLATAFORMA DE BRANDING (Output 9) ==='); if (plat.conteudo) parts.push(plat.conteudo); }
    return parts.join('\n');
  },

  parseOutput(rawText) {
    const extract = (tag) => {
      const m = rawText.match(new RegExp(`<${tag}>([\\s\\S]*?)</${tag}>`));
      return m ? m[1].trim() : '';
    };
    return {
      conteudo: extract('conteudo'),
      resumo_executivo: extract('resumo_executivo'),
      conclusoes: extract('conclusoes'),
      confianca: extract('confianca') || 'Media',
      fontes: 'Visão Geral + Plataforma (Método Ana Couto — One Page de Experiência)',
      gaps: extract('gaps') || '',
    };
  },
};
