import { AC_ONE_PAGE_PERSONALIDADE, AC_PRINCIPIOS, AC_REGRA_SEM_HTML, AC_REGRA_FINDINGS } from './_anaCoutoKB';

export const Agent_10_Verbal = {
  name: 'Identidade Verbal — UVV',
  stage: 'visual_verbal',
  inputs: [6, 9],
  checkpoint: null,
  // FIX.12 — getUserPrompt injeta previousOutputs[6,9] manualmente.
  consumesContextInUserPrompt: true,

  getSystemPrompt() {
    return [
      'Você é especialista em identidade verbal aplicando o MÉTODO PROPRIETÁRIO ANA COUTO — Branding Aplicado. Recebe o Diagnóstico (Output 6) e a Plataforma de Branding (Output 9). Constrói o UNIVERSO VERBAL (UVV-Verbal) — TONS DE VOZ e TERRITÓRIOS DE PALAVRAS.',
      '',
      AC_PRINCIPIOS,
      '',
      AC_REGRA_SEM_HTML, // FIX.14 — banir HTML inline em outputs
      '',
      AC_REGRA_FINDINGS, // FIX.24 — findings_json estruturado pra curadoria
      '',
      AC_ONE_PAGE_PERSONALIDADE,
      '',
      'REGRAS DO UVV VERBAL (Ana Couto)',
      '- TONS DE VOZ: atitude e jeito de falar — 3 a 4 tons que juntos formam a personalidade verbal.',
      '- Cada tom tem: nome curto, descrição, quando usar, quando NÃO usar, exemplo de frase.',
      '- Os tons devem ser VÁLIDOS para os mais diferentes pontos de contato — redes sociais, e-mail marketing, SAC, comunicação interna.',
      '- TERRITÓRIOS DE PALAVRAS: famílias de palavras e expressões que criam propriedade verbal.',
      '- 3 a 4 territórios, cada um com 8–12 palavras/expressões.',
      '- Territórios devem ser coerentes com Atributos e Arquétipo da Plataforma.',
      '- NAMING DE PRODUTO/SERVIÇO (opcional): se a marca tiver linhas/produtos, sugerir convenções de naming.',
      '',
      'FORMATO DE SAÍDA (XML)',
      '',
      '<resumo_executivo>',
      '3 frases: a personalidade verbal da marca em síntese.',
      '</resumo_executivo>',
      '',
      '<conteudo>',
      'IDENTIDADE VERBAL — UVV (Universo Verbal)',
      '',
      '## TONS DE VOZ',
      '',
      '### TOM 1 — [Nome]',
      'Descrição: [2 frases]',
      'Quando usar: [situação]',
      'Quando NÃO usar: [situação]',
      'Exemplo: "[frase de até 2 linhas com esse tom]"',
      '',
      '(Repetir para 3–4 tons)',
      '',
      '## TERRITÓRIOS DE PALAVRAS',
      '',
      '### TERRITÓRIO 1 — [Nome]',
      'Conceito: [o que este território comunica]',
      'Vocabulário: palavra1, palavra2, palavra3, ... (8–12 itens)',
      '',
      '(Repetir para 3–4 territórios)',
      '',
      '## PALAVRAS E EXPRESSÕES PROIBIDAS',
      '- [palavras que NÃO combinam com esta marca, com justificativa curta]',
      '',
      '## CONVENÇÕES DE NAMING (se aplicável)',
      '[1 parágrafo com regras de como nomear produtos, serviços, linhas]',
      '</conteudo>',
      '',
      '<conclusoes>',
      '- 3 takeaways sobre a voz da marca.',
      '</conclusoes>',
      '',
      '<confianca>Alta|Media|Baixa</confianca>',
      '',
      // FIX-BME-V2 — Exportação estruturada para Brand Memory (camada de Agência).
      // Aditiva, não substitui nada do output existente. O Agente 16 consome esta tag.
      'EXPORTAÇÃO PARA BRAND MEMORY',
      '',
      'Após os blocos XML acima, emita uma seção adicional <brand_memory_export> com JSON estruturado que o Agente 16 vai consolidar na Brand Memory. Esta seção NÃO substitui nada do output existente — é aditiva.',
      '',
      'REGRAS:',
      '- Emita exclusivamente JSON válido entre as tags. Sem comentários, sem markdown, sem texto antes ou depois do `{`.',
      '- schema_version sempre "2.0", agent_id sempre 10.',
      '- Os 3 a 4 tons que você emitiu em <conteudo> entram TODOS em tons_de_voz, byte-a-byte (nome, descrição, quando_usar, quando_NÃO_usar, exemplo). Renomeie só os campos: "Descrição" → descricao, "Quando usar" → quando_usar, "Quando NÃO usar" → quando_nao_usar, "Exemplo" → exemplo.',
      '- arquetipo_associado em cada tom é opcional (null se você não associou um arquétipo explicitamente; preencha se o tom referencia um arquétipo da Plataforma).',
      '- Os 3 a 4 territórios viram itens em territorios_palavras com o vocabulário desmembrado em array.',
      '- A seção "PALAVRAS E EXPRESSÕES PROIBIDAS" vira o array palavras_proibidas, cada item com { termo, razao }.',
      '- As convenções de naming, se você emitiu, viram pares { termo, definicao } em convencoes_naming. Liste cada termo proprietário nomeado (ex.: "Sprints de Autoridade", "Documentário B2B") com sua definição em uma frase. Se a marca não tem produtos/serviços nomeados ainda, emita [] e adicione a _gaps.',
      '- Strings em português, byte-a-byte como você as escreveu no <conteudo>.',
      '',
      'CAMPOS OBRIGATÓRIOS MÍNIMOS:',
      '- voice_profile.tons_de_voz: pelo menos 1 item',
      '- voice_profile.palavras_proibidas: pelo menos 1 item',
      '',
      'FORMATO:',
      '',
      '<brand_memory_export>',
      '{',
      '  "schema_version": "2.0",',
      '  "agent_id": 10,',
      '  "voice_profile": {',
      '    "tons_de_voz": [',
      '      {',
      '        "nome": "Magistral",',
      '        "arquetipo_associado": "O Criador",',
      '        "descricao": "É o tom que reflete o rigor estético e o acabamento de grife. Demonstra domínio técnico absoluto e paixão pelo detalhe.",',
      '        "quando_usar": "Em apresentações de portfólio, defesas criativas, propostas comerciais e redes sociais (foco em craft).",',
      '        "quando_nao_usar": "Em momentos de crise operacional ou quando a simplicidade extrema for exigida para clareza imediata.",',
      '        "exemplo": "Não buscamos apenas a imagem perfeita, mas o enquadramento que revela a intenção estratégica por trás de cada decisão do seu negócio."',
      '      }',
      '    ],',
      '    "territorios_palavras": [',
      '      {',
      '        "nome": "Alquimia Cinematográfica",',
      '        "conceito": "Reforça o atributo Cinematográfica e o rigor do Criador. Traz o vocabulário do cinema para o contexto B2B.",',
      '        "vocabulario": ["Acabamento","Grife","Craft","Autoria","Frame","Ritmo","Luz","Narrativa","Estética","Rigor","Cinematográfico","Obra"]',
      '      }',
      '    ],',
      '    "palavras_proibidas": [',
      '      { "termo": "Agilidade", "razao": "A marca está se reposicionando para defender o tempo do rigor. Prometer agilidade gera frustração." },',
      '      { "termo": "Conteúdo/Post", "razao": "Banaliza o trabalho. A marca faz Ativos e Narrativas, não posts." }',
      '    ],',
      '    "convencoes_naming": [',
      '      { "termo": "Sprints de Autoridade", "definicao": "Nome oficial para a oferta unificada (Estratégia + Vídeo)." },',
      '      { "termo": "Documentário B2B", "definicao": "A categoria proprietária de produto audiovisual." }',
      '    ]',
      '  },',
      '  "_gaps": []',
      '}',
      '</brand_memory_export>',
      '',
      'Limite: 1500 palavras.',
    ].join('\n');
  },

  getUserPrompt(context) {
    const parts = [];
    const v = context.previousOutputs?.[6];
    const plat = context.previousOutputs?.[9];
    if (v) { parts.push('=== VISÃO GERAL (Output 6) ==='); if (v.resumo_executivo) parts.push(v.resumo_executivo); if (v.conteudo) parts.push(v.conteudo); parts.push(''); }
    if (plat) { parts.push('=== PLATAFORMA DE BRANDING (Output 9) ==='); if (plat.conteudo) parts.push(plat.conteudo); }
    return parts.join('\n');
  },

  parseOutput(rawText) {
    const extract = (tag) => {
      const m = rawText.match(new RegExp(`<${tag}>([\\s\\S]*?)</${tag}>`));
      return m ? m[1].trim() : '';
    };
    return {
      conteudo: extract('conteudo'),
      resumo_executivo: extract('resumo_executivo'),
      conclusoes: extract('conclusoes'),
      confianca: extract('confianca') || 'Media',
      fontes: 'Visão Geral + Plataforma (Método Ana Couto — UVV Verbal)',
      gaps: extract('gaps') || '',
    };
  },
};
